### ISSUE TITLE
ICPReduceMatrix takes too long to be realtime

### ISSUE THREAD

**Issue by mali-tintash** [sjy234sjy234/KinectFusion-ios#3]
I am trying to optimise it for faster processing on iPhoneX. But from analysis, the major processing time is going into ICPReducerMatrix. I have modified the pipeline to use as less command buffers as I thought possible. But this ReducerMatrix already uses MPSMatrixMultiplication and surprisingly is super slow if we consider it being computed over GPU.

You mentioned that with GPGPU practices we can reach 30FPS on an iPhoneX, but I don't understand what to do with this part of the code. Can you please guide?

My guess for slower processing in multiplication is "probably" stride misalignment on matrices as input? But I could be wrong. What did you base the 30FPS suggestion on?

**Comment by sjy234sjy234** [comment]
try to write your own multiplication shader instead.



发自我的iPhone


------------------ Original ------------------

**Comment by mali-tintash** [comment]
How do I optimise for stride? all the routines for getting stride seem to be obsolete. Also, the ICPReduceMatrix takes "OccupiedPixelNumber" as input, which is only available when ICPPrepareMatrix is done "waitUntilCompleted" is there a way around it?

Secondly, because the number of "occupiedPixelNumber" is variable, we have to allocate a new buffer for each iteration. That seems to block the CPU on allocation and we lose about 1.2 ms before the kernel is launched. Do you have any suggestions for that?

**Comment by sjy234sjy234** [comment]
Estimate to give fix size buffer in the first place.

发自我的iPhone


------------------ Original ------------------

**Comment by mali-tintash** [comment]
I am unclear on how to estimate the occupied pixels returned from ICPPrepare. Any pointers please?

Do you have transpose + multiply kernel for metal written? if you can share

**Comment by sjy234sjy234** [comment]
There is an up bound(w*h). Set a fix ratio, such as 0.6 * w * h. Multiplication is quite straightforward, try it by yourself.



发自我的iPhone


------------------ Original ------------------
