### ISSUE TITLE
Bilateral filtering on depth map is missing w.r.t Original Kinect Fusion paper

### ISSUE THREAD

**Issue by mali-tintash** [sjy234sjy234/KinectFusion-ios#4]
Hi,
Is there any particular reason you aren't using bilateral filtering on depth maps before processing them?

In every other paper and even the original Kinect Fusion paper uses bilateral filtering before passing on depth maps for further processing.

**Comment by sjy234sjy234** [comment]
I checked the spatial consistency for single frame and found it is promising so that I skipped the filter directly. Still, you can apply the filter to see if there is any gain or not.

**Comment by mali-tintash** [comment]
> I checked the spatial consistency for single frame and found it is promising so that I skipped the filter directly. Still, you can apply the filter to see if there is any gain or not.

It didn't help noticably.
